[package]
name = "common-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
uefi_imp = ["uefi"] 

[dependencies]
uefi = { version = "0.15.2", optional = true }

